version: '3.8'

services:
  flask-app:
    build: .
    ports:
      # Allows changing the port (5001 or 5002)
      - "${HOST_PORT:-5000}:5000"
    environment:
      # Injects the environment name for the badge
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - GITHUB_SHA=${GITHUB_SHA:-unknown}
      - DEPLOY_TIME=${DEPLOY_TIME:-unknown}
      - APP_VERSION=week4-release
    restart: always